language: node_js
node_js:
- '8'
sudo: false
before_deploy:
- echo $TRAVIS_COMMIT
- echo $TRAVIS_TAG
- echo $TRAVIS_BRANCH
- echo $TRAVIS_BUILD_NUMBER
- echo $TRAVIS_REPO_SLUG
- node run.js
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  api_key: $GITHUB_TOKEN  
  file:
    - "*.tar.gz"
    - platform.json
  file_glob: true
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    tags: true
